<?php

namespace App\Bundle\UserBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepo
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class UserRepo extends EntityRepository
{
}
